// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/bblfsh/sdk/protocol/generated.proto

package github.com.bblfsh.sdk.protocol;

public final class Generated {
  private Generated() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Encoding is the encoding used for the content string. Currently only
   * UTF-8 or Base64 encodings are supported. You should use UTF-8 if you can
   * and Base64 as a fallback.
   * </pre>
   *
   * Protobuf enum {@code github.com.bblfsh.sdk.protocol.Encoding}
   */
  public enum Encoding
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * UTF8 encoding
     * </pre>
     *
     * <code>UTF8 = 0 [(.gogoproto.enumvalue_customname) = "UTF8"];</code>
     */
    UTF8(0),
    /**
     * <pre>
     * Base64 encoding
     * </pre>
     *
     * <code>BASE64 = 1 [(.gogoproto.enumvalue_customname) = "Base64"];</code>
     */
    BASE64(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * UTF8 encoding
     * </pre>
     *
     * <code>UTF8 = 0 [(.gogoproto.enumvalue_customname) = "UTF8"];</code>
     */
    public static final int UTF8_VALUE = 0;
    /**
     * <pre>
     * Base64 encoding
     * </pre>
     *
     * <code>BASE64 = 1 [(.gogoproto.enumvalue_customname) = "Base64"];</code>
     */
    public static final int BASE64_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Encoding valueOf(int value) {
      return forNumber(value);
    }

    public static Encoding forNumber(int value) {
      switch (value) {
        case 0: return UTF8;
        case 1: return BASE64;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Encoding>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Encoding> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Encoding>() {
            public Encoding findValueByNumber(int number) {
              return Encoding.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return github.com.bblfsh.sdk.protocol.Generated.getDescriptor().getEnumTypes().get(0);
    }

    private static final Encoding[] VALUES = values();

    public static Encoding valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Encoding(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:github.com.bblfsh.sdk.protocol.Encoding)
  }

  /**
   * <pre>
   * Status is the status of a response.
   * </pre>
   *
   * Protobuf enum {@code github.com.bblfsh.sdk.protocol.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Ok status code.
     * </pre>
     *
     * <code>OK = 0 [(.gogoproto.enumvalue_customname) = "Ok"];</code>
     */
    OK(0),
    /**
     * <pre>
     * Error status code. It is replied when the driver has got the AST with errors.
     * </pre>
     *
     * <code>ERROR = 1 [(.gogoproto.enumvalue_customname) = "Error"];</code>
     */
    ERROR(1),
    /**
     * <pre>
     * Fatal status code. It is replied when the driver hasn't could get the AST.
     * </pre>
     *
     * <code>FATAL = 2 [(.gogoproto.enumvalue_customname) = "Fatal"];</code>
     */
    FATAL(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Ok status code.
     * </pre>
     *
     * <code>OK = 0 [(.gogoproto.enumvalue_customname) = "Ok"];</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <pre>
     * Error status code. It is replied when the driver has got the AST with errors.
     * </pre>
     *
     * <code>ERROR = 1 [(.gogoproto.enumvalue_customname) = "Error"];</code>
     */
    public static final int ERROR_VALUE = 1;
    /**
     * <pre>
     * Fatal status code. It is replied when the driver hasn't could get the AST.
     * </pre>
     *
     * <code>FATAL = 2 [(.gogoproto.enumvalue_customname) = "Fatal"];</code>
     */
    public static final int FATAL_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return ERROR;
        case 2: return FATAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return github.com.bblfsh.sdk.protocol.Generated.getDescriptor().getEnumTypes().get(1);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:github.com.bblfsh.sdk.protocol.Status)
  }

  public interface ParseRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:github.com.bblfsh.sdk.protocol.ParseRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string filename = 1;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>string filename = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>string language = 2;</code>
     */
    java.lang.String getLanguage();
    /**
     * <code>string language = 2;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
     */
    int getEncodingValue();
    /**
     * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
     */
    github.com.bblfsh.sdk.protocol.Generated.Encoding getEncoding();
  }
  /**
   * <pre>
   * ParseRequest is a request to parse a file and get its UAST.
   * </pre>
   *
   * Protobuf type {@code github.com.bblfsh.sdk.protocol.ParseRequest}
   */
  public  static final class ParseRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:github.com.bblfsh.sdk.protocol.ParseRequest)
      ParseRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParseRequest.newBuilder() to construct.
    private ParseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseRequest() {
      filename_ = "";
      language_ = "";
      content_ = "";
      encoding_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParseRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filename_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              language_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              encoding_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              github.com.bblfsh.sdk.protocol.Generated.ParseRequest.class, github.com.bblfsh.sdk.protocol.Generated.ParseRequest.Builder.class);
    }

    public static final int FILENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object filename_;
    /**
     * <code>string filename = 1;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filename_ = s;
        return s;
      }
    }
    /**
     * <code>string filename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANGUAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object language_;
    /**
     * <code>string language = 2;</code>
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <code>string language = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCODING_FIELD_NUMBER = 4;
    private int encoding_;
    /**
     * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
     */
    public int getEncodingValue() {
      return encoding_;
    }
    /**
     * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
     */
    public github.com.bblfsh.sdk.protocol.Generated.Encoding getEncoding() {
      github.com.bblfsh.sdk.protocol.Generated.Encoding result = github.com.bblfsh.sdk.protocol.Generated.Encoding.valueOf(encoding_);
      return result == null ? github.com.bblfsh.sdk.protocol.Generated.Encoding.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFilenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
      }
      if (!getLanguageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, language_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (encoding_ != github.com.bblfsh.sdk.protocol.Generated.Encoding.UTF8.getNumber()) {
        output.writeEnum(4, encoding_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFilenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
      }
      if (!getLanguageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, language_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (encoding_ != github.com.bblfsh.sdk.protocol.Generated.Encoding.UTF8.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, encoding_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof github.com.bblfsh.sdk.protocol.Generated.ParseRequest)) {
        return super.equals(obj);
      }
      github.com.bblfsh.sdk.protocol.Generated.ParseRequest other = (github.com.bblfsh.sdk.protocol.Generated.ParseRequest) obj;

      boolean result = true;
      result = result && getFilename()
          .equals(other.getFilename());
      result = result && getLanguage()
          .equals(other.getLanguage());
      result = result && getContent()
          .equals(other.getContent());
      result = result && encoding_ == other.encoding_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getFilename().hashCode();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + ENCODING_FIELD_NUMBER;
      hash = (53 * hash) + encoding_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(github.com.bblfsh.sdk.protocol.Generated.ParseRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ParseRequest is a request to parse a file and get its UAST.
     * </pre>
     *
     * Protobuf type {@code github.com.bblfsh.sdk.protocol.ParseRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:github.com.bblfsh.sdk.protocol.ParseRequest)
        github.com.bblfsh.sdk.protocol.Generated.ParseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                github.com.bblfsh.sdk.protocol.Generated.ParseRequest.class, github.com.bblfsh.sdk.protocol.Generated.ParseRequest.Builder.class);
      }

      // Construct using github.com.bblfsh.sdk.protocol.Generated.ParseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        filename_ = "";

        language_ = "";

        content_ = "";

        encoding_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_descriptor;
      }

      public github.com.bblfsh.sdk.protocol.Generated.ParseRequest getDefaultInstanceForType() {
        return github.com.bblfsh.sdk.protocol.Generated.ParseRequest.getDefaultInstance();
      }

      public github.com.bblfsh.sdk.protocol.Generated.ParseRequest build() {
        github.com.bblfsh.sdk.protocol.Generated.ParseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public github.com.bblfsh.sdk.protocol.Generated.ParseRequest buildPartial() {
        github.com.bblfsh.sdk.protocol.Generated.ParseRequest result = new github.com.bblfsh.sdk.protocol.Generated.ParseRequest(this);
        result.filename_ = filename_;
        result.language_ = language_;
        result.content_ = content_;
        result.encoding_ = encoding_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof github.com.bblfsh.sdk.protocol.Generated.ParseRequest) {
          return mergeFrom((github.com.bblfsh.sdk.protocol.Generated.ParseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(github.com.bblfsh.sdk.protocol.Generated.ParseRequest other) {
        if (other == github.com.bblfsh.sdk.protocol.Generated.ParseRequest.getDefaultInstance()) return this;
        if (!other.getFilename().isEmpty()) {
          filename_ = other.filename_;
          onChanged();
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.encoding_ != 0) {
          setEncodingValue(other.getEncodingValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        github.com.bblfsh.sdk.protocol.Generated.ParseRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (github.com.bblfsh.sdk.protocol.Generated.ParseRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <code>string filename = 1;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder clearFilename() {
        
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>string filename = 1;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filename_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <code>string language = 2;</code>
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string language = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string language = 2;</code>
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string language = 2;</code>
       */
      public Builder clearLanguage() {
        
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>string language = 2;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        language_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int encoding_ = 0;
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
       */
      public int getEncodingValue() {
        return encoding_;
      }
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
       */
      public Builder setEncodingValue(int value) {
        encoding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
       */
      public github.com.bblfsh.sdk.protocol.Generated.Encoding getEncoding() {
        github.com.bblfsh.sdk.protocol.Generated.Encoding result = github.com.bblfsh.sdk.protocol.Generated.Encoding.valueOf(encoding_);
        return result == null ? github.com.bblfsh.sdk.protocol.Generated.Encoding.UNRECOGNIZED : result;
      }
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
       */
      public Builder setEncoding(github.com.bblfsh.sdk.protocol.Generated.Encoding value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        encoding_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Encoding encoding = 4;</code>
       */
      public Builder clearEncoding() {
        
        encoding_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:github.com.bblfsh.sdk.protocol.ParseRequest)
    }

    // @@protoc_insertion_point(class_scope:github.com.bblfsh.sdk.protocol.ParseRequest)
    private static final github.com.bblfsh.sdk.protocol.Generated.ParseRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new github.com.bblfsh.sdk.protocol.Generated.ParseRequest();
    }

    public static github.com.bblfsh.sdk.protocol.Generated.ParseRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseRequest>
        PARSER = new com.google.protobuf.AbstractParser<ParseRequest>() {
      public ParseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ParseRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParseRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseRequest> getParserForType() {
      return PARSER;
    }

    public github.com.bblfsh.sdk.protocol.Generated.ParseRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParseResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:github.com.bblfsh.sdk.protocol.ParseResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
     */
    github.com.bblfsh.sdk.protocol.Generated.Status getStatus();

    /**
     * <code>repeated string errors = 2;</code>
     */
    java.util.List<java.lang.String>
        getErrorsList();
    /**
     * <code>repeated string errors = 2;</code>
     */
    int getErrorsCount();
    /**
     * <code>repeated string errors = 2;</code>
     */
    java.lang.String getErrors(int index);
    /**
     * <code>repeated string errors = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorsBytes(int index);

    /**
     * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
     */
    boolean hasUast();
    /**
     * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
     */
    github.com.bblfsh.sdk.uast.Generated.Node getUast();
    /**
     * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
     */
    github.com.bblfsh.sdk.uast.Generated.NodeOrBuilder getUastOrBuilder();
  }
  /**
   * <pre>
   * ParseResponse is the reply to ParseRequest.
   * </pre>
   *
   * Protobuf type {@code github.com.bblfsh.sdk.protocol.ParseResponse}
   */
  public  static final class ParseResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:github.com.bblfsh.sdk.protocol.ParseResponse)
      ParseResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ParseResponse.newBuilder() to construct.
    private ParseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseResponse() {
      status_ = 0;
      errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParseResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                errors_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              errors_.add(s);
              break;
            }
            case 26: {
              github.com.bblfsh.sdk.uast.Generated.Node.Builder subBuilder = null;
              if (uast_ != null) {
                subBuilder = uast_.toBuilder();
              }
              uast_ = input.readMessage(github.com.bblfsh.sdk.uast.Generated.Node.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(uast_);
                uast_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          errors_ = errors_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              github.com.bblfsh.sdk.protocol.Generated.ParseResponse.class, github.com.bblfsh.sdk.protocol.Generated.ParseResponse.Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
     */
    public github.com.bblfsh.sdk.protocol.Generated.Status getStatus() {
      github.com.bblfsh.sdk.protocol.Generated.Status result = github.com.bblfsh.sdk.protocol.Generated.Status.valueOf(status_);
      return result == null ? github.com.bblfsh.sdk.protocol.Generated.Status.UNRECOGNIZED : result;
    }

    public static final int ERRORS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList errors_;
    /**
     * <code>repeated string errors = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getErrorsList() {
      return errors_;
    }
    /**
     * <code>repeated string errors = 2;</code>
     */
    public int getErrorsCount() {
      return errors_.size();
    }
    /**
     * <code>repeated string errors = 2;</code>
     */
    public java.lang.String getErrors(int index) {
      return errors_.get(index);
    }
    /**
     * <code>repeated string errors = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorsBytes(int index) {
      return errors_.getByteString(index);
    }

    public static final int UAST_FIELD_NUMBER = 3;
    private github.com.bblfsh.sdk.uast.Generated.Node uast_;
    /**
     * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
     */
    public boolean hasUast() {
      return uast_ != null;
    }
    /**
     * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
     */
    public github.com.bblfsh.sdk.uast.Generated.Node getUast() {
      return uast_ == null ? github.com.bblfsh.sdk.uast.Generated.Node.getDefaultInstance() : uast_;
    }
    /**
     * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
     */
    public github.com.bblfsh.sdk.uast.Generated.NodeOrBuilder getUastOrBuilder() {
      return getUast();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != github.com.bblfsh.sdk.protocol.Generated.Status.OK.getNumber()) {
        output.writeEnum(1, status_);
      }
      for (int i = 0; i < errors_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errors_.getRaw(i));
      }
      if (uast_ != null) {
        output.writeMessage(3, getUast());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != github.com.bblfsh.sdk.protocol.Generated.Status.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errors_.size(); i++) {
          dataSize += computeStringSizeNoTag(errors_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getErrorsList().size();
      }
      if (uast_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUast());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof github.com.bblfsh.sdk.protocol.Generated.ParseResponse)) {
        return super.equals(obj);
      }
      github.com.bblfsh.sdk.protocol.Generated.ParseResponse other = (github.com.bblfsh.sdk.protocol.Generated.ParseResponse) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      result = result && getErrorsList()
          .equals(other.getErrorsList());
      result = result && (hasUast() == other.hasUast());
      if (hasUast()) {
        result = result && getUast()
            .equals(other.getUast());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (getErrorsCount() > 0) {
        hash = (37 * hash) + ERRORS_FIELD_NUMBER;
        hash = (53 * hash) + getErrorsList().hashCode();
      }
      if (hasUast()) {
        hash = (37 * hash) + UAST_FIELD_NUMBER;
        hash = (53 * hash) + getUast().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(github.com.bblfsh.sdk.protocol.Generated.ParseResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * ParseResponse is the reply to ParseRequest.
     * </pre>
     *
     * Protobuf type {@code github.com.bblfsh.sdk.protocol.ParseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:github.com.bblfsh.sdk.protocol.ParseResponse)
        github.com.bblfsh.sdk.protocol.Generated.ParseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                github.com.bblfsh.sdk.protocol.Generated.ParseResponse.class, github.com.bblfsh.sdk.protocol.Generated.ParseResponse.Builder.class);
      }

      // Construct using github.com.bblfsh.sdk.protocol.Generated.ParseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (uastBuilder_ == null) {
          uast_ = null;
        } else {
          uast_ = null;
          uastBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return github.com.bblfsh.sdk.protocol.Generated.internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_descriptor;
      }

      public github.com.bblfsh.sdk.protocol.Generated.ParseResponse getDefaultInstanceForType() {
        return github.com.bblfsh.sdk.protocol.Generated.ParseResponse.getDefaultInstance();
      }

      public github.com.bblfsh.sdk.protocol.Generated.ParseResponse build() {
        github.com.bblfsh.sdk.protocol.Generated.ParseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public github.com.bblfsh.sdk.protocol.Generated.ParseResponse buildPartial() {
        github.com.bblfsh.sdk.protocol.Generated.ParseResponse result = new github.com.bblfsh.sdk.protocol.Generated.ParseResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.status_ = status_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          errors_ = errors_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.errors_ = errors_;
        if (uastBuilder_ == null) {
          result.uast_ = uast_;
        } else {
          result.uast_ = uastBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof github.com.bblfsh.sdk.protocol.Generated.ParseResponse) {
          return mergeFrom((github.com.bblfsh.sdk.protocol.Generated.ParseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(github.com.bblfsh.sdk.protocol.Generated.ParseResponse other) {
        if (other == github.com.bblfsh.sdk.protocol.Generated.ParseResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.errors_.isEmpty()) {
          if (errors_.isEmpty()) {
            errors_ = other.errors_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureErrorsIsMutable();
            errors_.addAll(other.errors_);
          }
          onChanged();
        }
        if (other.hasUast()) {
          mergeUast(other.getUast());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        github.com.bblfsh.sdk.protocol.Generated.ParseResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (github.com.bblfsh.sdk.protocol.Generated.ParseResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
       */
      public github.com.bblfsh.sdk.protocol.Generated.Status getStatus() {
        github.com.bblfsh.sdk.protocol.Generated.Status result = github.com.bblfsh.sdk.protocol.Generated.Status.valueOf(status_);
        return result == null ? github.com.bblfsh.sdk.protocol.Generated.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
       */
      public Builder setStatus(github.com.bblfsh.sdk.protocol.Generated.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.github.com.bblfsh.sdk.protocol.Status status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureErrorsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          errors_ = new com.google.protobuf.LazyStringArrayList(errors_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getErrorsList() {
        return errors_.getUnmodifiableView();
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public int getErrorsCount() {
        return errors_.size();
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public java.lang.String getErrors(int index) {
        return errors_.get(index);
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorsBytes(int index) {
        return errors_.getByteString(index);
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public Builder setErrors(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorsIsMutable();
        errors_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public Builder addErrors(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorsIsMutable();
        errors_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public Builder addAllErrors(
          java.lang.Iterable<java.lang.String> values) {
        ensureErrorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errors_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public Builder clearErrors() {
        errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errors = 2;</code>
       */
      public Builder addErrorsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureErrorsIsMutable();
        errors_.add(value);
        onChanged();
        return this;
      }

      private github.com.bblfsh.sdk.uast.Generated.Node uast_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          github.com.bblfsh.sdk.uast.Generated.Node, github.com.bblfsh.sdk.uast.Generated.Node.Builder, github.com.bblfsh.sdk.uast.Generated.NodeOrBuilder> uastBuilder_;
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      public boolean hasUast() {
        return uastBuilder_ != null || uast_ != null;
      }
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      public github.com.bblfsh.sdk.uast.Generated.Node getUast() {
        if (uastBuilder_ == null) {
          return uast_ == null ? github.com.bblfsh.sdk.uast.Generated.Node.getDefaultInstance() : uast_;
        } else {
          return uastBuilder_.getMessage();
        }
      }
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      public Builder setUast(github.com.bblfsh.sdk.uast.Generated.Node value) {
        if (uastBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          uast_ = value;
          onChanged();
        } else {
          uastBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      public Builder setUast(
          github.com.bblfsh.sdk.uast.Generated.Node.Builder builderForValue) {
        if (uastBuilder_ == null) {
          uast_ = builderForValue.build();
          onChanged();
        } else {
          uastBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      public Builder mergeUast(github.com.bblfsh.sdk.uast.Generated.Node value) {
        if (uastBuilder_ == null) {
          if (uast_ != null) {
            uast_ =
              github.com.bblfsh.sdk.uast.Generated.Node.newBuilder(uast_).mergeFrom(value).buildPartial();
          } else {
            uast_ = value;
          }
          onChanged();
        } else {
          uastBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      public Builder clearUast() {
        if (uastBuilder_ == null) {
          uast_ = null;
          onChanged();
        } else {
          uast_ = null;
          uastBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      public github.com.bblfsh.sdk.uast.Generated.Node.Builder getUastBuilder() {
        
        onChanged();
        return getUastFieldBuilder().getBuilder();
      }
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      public github.com.bblfsh.sdk.uast.Generated.NodeOrBuilder getUastOrBuilder() {
        if (uastBuilder_ != null) {
          return uastBuilder_.getMessageOrBuilder();
        } else {
          return uast_ == null ?
              github.com.bblfsh.sdk.uast.Generated.Node.getDefaultInstance() : uast_;
        }
      }
      /**
       * <code>.github.com.bblfsh.sdk.uast.Node uast = 3 [(.gogoproto.customname) = "UAST"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          github.com.bblfsh.sdk.uast.Generated.Node, github.com.bblfsh.sdk.uast.Generated.Node.Builder, github.com.bblfsh.sdk.uast.Generated.NodeOrBuilder> 
          getUastFieldBuilder() {
        if (uastBuilder_ == null) {
          uastBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              github.com.bblfsh.sdk.uast.Generated.Node, github.com.bblfsh.sdk.uast.Generated.Node.Builder, github.com.bblfsh.sdk.uast.Generated.NodeOrBuilder>(
                  getUast(),
                  getParentForChildren(),
                  isClean());
          uast_ = null;
        }
        return uastBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:github.com.bblfsh.sdk.protocol.ParseResponse)
    }

    // @@protoc_insertion_point(class_scope:github.com.bblfsh.sdk.protocol.ParseResponse)
    private static final github.com.bblfsh.sdk.protocol.Generated.ParseResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new github.com.bblfsh.sdk.protocol.Generated.ParseResponse();
    }

    public static github.com.bblfsh.sdk.protocol.Generated.ParseResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseResponse>
        PARSER = new com.google.protobuf.AbstractParser<ParseResponse>() {
      public ParseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ParseResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParseResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseResponse> getParserForType() {
      return PARSER;
    }

    public github.com.bblfsh.sdk.protocol.Generated.ParseResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.github.com/bblfsh/sdk/protocol/generat" +
      "ed.proto\022\036github.com.bblfsh.sdk.protocol" +
      "\032-github.com/gogo/protobuf/gogoproto/gog" +
      "o.proto\032*github.com/bblfsh/sdk/uast/gene" +
      "rated.proto\"\211\001\n\014ParseRequest\022\020\n\010filename" +
      "\030\001 \001(\t\022\020\n\010language\030\002 \001(\t\022\017\n\007content\030\003 \001(" +
      "\t\022:\n\010encoding\030\004 \001(\0162(.github.com.bblfsh." +
      "sdk.protocol.Encoding:\010\210\240\037\000\360\241\037\000\"\233\001\n\rPars" +
      "eResponse\0226\n\006status\030\001 \001(\0162&.github.com.b" +
      "blfsh.sdk.protocol.Status\022\016\n\006errors\030\002 \003(",
      "\t\0228\n\004uast\030\003 \001(\0132 .github.com.bblfsh.sdk." +
      "uast.NodeB\010\342\336\037\004UAST:\010\210\240\037\000\360\241\037\000*D\n\010Encodin" +
      "g\022\022\n\004UTF8\020\000\032\010\212\235 \004UTF8\022\026\n\006BASE64\020\001\032\n\212\235 \006B" +
      "ase64\032\014\300\244\036\000\210\243\036\000\250\244\036\000*R\n\006Status\022\016\n\002OK\020\000\032\006\212" +
      "\235 \002Ok\022\024\n\005ERROR\020\001\032\t\212\235 \005Error\022\024\n\005FATAL\020\002\032\t" +
      "\212\235 \005Fatal\032\014\300\244\036\000\210\243\036\000\250\244\036\0002w\n\017ProtocolServi" +
      "ce\022d\n\005Parse\022,.github.com.bblfsh.sdk.prot" +
      "ocol.ParseRequest\032-.github.com.bblfsh.sd" +
      "k.protocol.ParseResponseB\022Z\010protocol\240\343\036\001" +
      "\340\342\036\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          github.com.bblfsh.sdk.uast.Generated.getDescriptor(),
        }, assigner);
    internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_github_com_bblfsh_sdk_protocol_ParseRequest_descriptor,
        new java.lang.String[] { "Filename", "Language", "Content", "Encoding", });
    internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_github_com_bblfsh_sdk_protocol_ParseResponse_descriptor,
        new java.lang.String[] { "Status", "Errors", "Uast", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.customname);
    registry.add(com.google.protobuf.GoGoProtos.enumdecl);
    registry.add(com.google.protobuf.GoGoProtos.enumvalueCustomname);
    registry.add(com.google.protobuf.GoGoProtos.goprotoEnumPrefix);
    registry.add(com.google.protobuf.GoGoProtos.goprotoEnumStringer);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    registry.add(com.google.protobuf.GoGoProtos.protosizerAll);
    registry.add(com.google.protobuf.GoGoProtos.sizerAll);
    registry.add(com.google.protobuf.GoGoProtos.typedecl);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    github.com.bblfsh.sdk.uast.Generated.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
